version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:6000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=portfolio_app_dev
      - SECRET_KEY=super-secret-key-development
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - JWT_SECRET_KEY=default-jwt-secret
      - JWT_ACCESS_TOKEN_EXPIRES=3600
      - JWT_REFRESH_TOKEN_EXPIRES=3600
      - JWT_BLACKLIST_ENABLED=True
      - JWT_BLACKLIST_TOKEN_CHECKS=access,refresh
      - CORS_HEADERS=Content-Type
    networks:
      - local-docker-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:3000"
    networks:
      - local-docker-network
  
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    ports:
      - "5001:80"
    networks:
      - local-docker-network

  proxy-manager:
    container_name: proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - proxy_data:/data
      - proxy_letsencrypt:/etc/letsencrypt
    networks:
      - local-docker-network
    depends_on:
      - backend
      - frontend
      - excalidraw

networks:
  local-docker-network:
    name: local-docker-network
    driver: bridge

volumes:
  proxy_data:
    name: proxy-data
  proxy_letsencrypt:
    name: proxy-letsencrypt 