version: "3"

services:
  mysql:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - local-docker-network

  backend:
    build:
      context: ./backend
    container_name: portfolio_app_backend
    environment:
      FLASK_ENV: production
    ports:
      - "6000:6000"
    networks:
      - local-docker-network

  frontend:
    build:
      context: ./frontend
    container_name: portfolio_app_frontend
    ports:
      - "3000:3000"
    networks:
      - local-docker-network

  proxy-manager:
    container_name: portfolio_proxy-manager
    image: docker.io/jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - local-docker-network

  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: ruizdev7-portfolio-excalidraw-1
    ports:
      - "5001:80"
    networks:
      - local-docker-network

networks:
  local-docker-network:
    name: local-docker-network
    driver: bridge

volumes:
  mysql-data:
