version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "6000:6000" # Cambiar el puerto mapeado en el host
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4000"

  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306" # Cambiar el puerto mapeado en el host
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: