version: "3.8"
services:
    backend:
        build:
            context: ./backend
        ports:
            - 6000:6000
        networks:
            - local-docker-network
        container_name: portfolio_app_backend
        image: portfolio_app_backend:1.0.0
        environment:
            - FLASK_ENV=production
    mysql:
        container_name: mysql_db
        environment:
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - local-docker-network
        image: mysql
networks:
    local-docker-network:
        external: true
        name: local-docker-network
volumes:
    mysql-data:
        external:
            name: mysql-data