services:
  backend:
    image: ruizdev7/portfolio-backend:REPLACE_TAG
    container_name: backend
    env_file:
      - backend/.env.production
    networks:
      - local-docker-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: ruizdev7/portfolio-frontend:REPLACE_TAG
    container_name: frontend
    networks:
      - local-docker-network

  docs:
    build:
      context: ../ruizdev7_portfolio_docs  # Cambia esto si tu Dockerfile está en otro lado
    container_name: docs
    networks:
      - local-docker-network
    restart: unless-stopped

  proxy-manager:
    container_name: proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - proxy_data:/data
      - proxy_letsencrypt:/etc/letsencrypt
    networks:
      - local-docker-network
    depends_on:
      - backend
      - frontend
      - docs

networks:
  local-docker-network:
    name: local-docker-network
    driver: bridge

volumes:
  proxy_data:
    name: proxy-data
  proxy_letsencrypt:
    name: proxy-letsencrypt