FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Instala herramientas útiles para desarrollo (opcional)
RUN apt-get update && \
    apt-get install -y vim && \
    rm -rf /var/lib/apt/lists/*

COPY . .

ENV FLASK_ENV=development

EXPOSE 6000

CMD ["flask", "run", "--host=0.0.0.0", "--port=6000"] 