#!/bin/bash

# Quick Test - Copy and paste these commands

BASE_URL="http://localhost:5000/api/v1"

echo "🧪 TEST RÁPIDO - CREAR AI AGENT"
echo "================================"
echo ""
echo "Copia y pega estos comandos uno por uno:"
echo ""
echo "1️⃣ LOGIN (reemplaza EMAIL y PASSWORD):"
echo "----------------------------------------"
echo "curl -X POST $BASE_URL/token \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\": \"TU_EMAIL\", \"password\": \"TU_PASSWORD\"}'"
echo ""
echo "Copia el 'access_token' de la respuesta"
echo ""
echo "2️⃣ VERIFICAR PERMISOS:"
echo "----------------------------------------"
echo "curl -X GET $BASE_URL/my-permissions \\"
echo "  -H 'Authorization: Bearer TU_TOKEN'"
echo ""
echo "3️⃣ CREAR AGENT:"
echo "----------------------------------------"
echo "curl -X POST $BASE_URL/ai/agents \\"
echo "  -H 'Authorization: Bearer TU_TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"name\": \"Financial Analyzer\","
echo "    \"agent_type\": \"financial\","
echo "    \"description\": \"Test agent\","
echo "    \"model_name\": \"gpt-4\","
echo "    \"confidence_threshold\": 0.75"
echo "  }'"
echo ""
echo "================================"
echo "Si recibes 403, el problema es el token."
echo "Asegúrate de usar el token MÁS RECIENTE del login."

