"""Add photos field to pumps table for multiple photo support

Revision ID: 0ec259cbfcff
Revises: ab01df4cfbf0
Create Date: 2025-07-29 13:19:10.971432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec259cbfcff'
down_revision = 'ab01df4cfbf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_pumps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_pumps', schema=None) as batch_op:
        batch_op.drop_column('photos')

    # ### end Alembic commands ###
