"""First migrate

Revision ID: 1637205ddebb
Revises: 
Create Date: 2023-10-02 11:59:23.834043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1637205ddebb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_auto_perceived_gender',
    sa.Column('ccn_auto_perceived_gender', sa.Integer(), nullable=False),
    sa.Column('auto_perceived_gender', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('ccn_auto_perceived_gender')
    )
    op.create_table('tbl_user',
    sa.Column('ccn_user', sa.Integer(), nullable=False),
    sa.Column('number_id_user', sa.BigInteger(), nullable=False),
    sa.Column('first_name_user', sa.String(length=60), nullable=False),
    sa.Column('middle_name_user', sa.String(length=60), nullable=True),
    sa.Column('last_name_user', sa.String(length=60), nullable=True),
    sa.Column('birthdate_user', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('auto_perceived_gender', sa.Integer(), nullable=True),
    sa.Column('email_user', sa.String(length=100), nullable=False),
    sa.Column('cellphone_user', sa.BigInteger(), nullable=False),
    sa.Column('terms_and_conditions', sa.String(length=10), nullable=False),
    sa.Column('profile_picture_user', sa.String(length=255), nullable=True),
    sa.Column('password_user', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['auto_perceived_gender'], ['tbl_auto_perceived_gender.ccn_auto_perceived_gender'], ),
    sa.PrimaryKeyConstraint('ccn_user'),
    sa.UniqueConstraint('number_id_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_user')
    op.drop_table('tbl_auto_perceived_gender')
    # ### end Alembic commands ###
