"""Adding test_001

Revision ID: 2b4545f75e94
Revises: 
Create Date: 2024-06-23 19:56:19.117944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4545f75e94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_categories',
    sa.Column('ccn_category', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description_categories', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ccn_category'),
    sa.UniqueConstraint('category')
    )
    op.create_table('tbl_project',
    sa.Column('ccn_project', sa.Integer(), nullable=False),
    sa.Column('title_project', sa.String(length=100), nullable=False),
    sa.Column('description_project', sa.String(length=300), nullable=False),
    sa.Column('pdf_software_requirement', sa.LargeBinary(), nullable=True),
    sa.Column('image_entity_relationship', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('ccn_project')
    )
    op.create_table('tbl_tags',
    sa.Column('ccn_tag', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ccn_tag'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('tbl_user',
    sa.Column('ccn_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email_user', sa.String(length=100), nullable=False),
    sa.Column('password_user', sa.String(length=300), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ccn_user'),
    sa.UniqueConstraint('email_user'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tbl_post',
    sa.Column('ccn_post', sa.Integer(), nullable=False),
    sa.Column('ccn_author', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ccn_author'], ['tbl_user.ccn_user'], ),
    sa.PrimaryKeyConstraint('ccn_post'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tbl_comment',
    sa.Column('ccn_comment', sa.Integer(), nullable=False),
    sa.Column('ccn_post', sa.Integer(), nullable=False),
    sa.Column('ccn_author', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ccn_author'], ['tbl_user.ccn_user'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ccn_post'], ['tbl_post.ccn_post'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ccn_comment')
    )
    op.create_table('tbl_post_categories',
    sa.Column('ccn_post', sa.Integer(), nullable=False),
    sa.Column('ccn_category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ccn_category'], ['tbl_categories.ccn_category'], ),
    sa.ForeignKeyConstraint(['ccn_post'], ['tbl_post.ccn_post'], ),
    sa.PrimaryKeyConstraint('ccn_post', 'ccn_category')
    )
    op.create_table('tbl_post_tags',
    sa.Column('ccn_post', sa.Integer(), nullable=False),
    sa.Column('ccn_tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ccn_post'], ['tbl_post.ccn_post'], ),
    sa.ForeignKeyConstraint(['ccn_tag'], ['tbl_tags.ccn_tag'], ),
    sa.PrimaryKeyConstraint('ccn_post', 'ccn_tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_post_tags')
    op.drop_table('tbl_post_categories')
    op.drop_table('tbl_comment')
    op.drop_table('tbl_post')
    op.drop_table('tbl_user')
    op.drop_table('tbl_tags')
    op.drop_table('tbl_project')
    op.drop_table('tbl_categories')
    # ### end Alembic commands ###
