"""Fixind tbl_writer relationships with tbl_type_id 2

Revision ID: 2cf87139fda2
Revises: f55cd62645d3
Create Date: 2023-09-27 22:32:28.692651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2cf87139fda2'
down_revision = 'f55cd62645d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_type_id', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.String(length=3), nullable=False))
        batch_op.drop_column('id_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_type_id', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_type', mysql.VARCHAR(length=3), nullable=False))
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
