"""Fix tbl_writer

Revision ID: 45cba2cc3b6b
Revises: d1346693f38e
Create Date: 2023-09-26 21:18:05.842551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cba2cc3b6b'
down_revision = 'd1346693f38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_writer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth_writer', sa.Date(), nullable=False))
        batch_op.drop_column('birthday_writer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_writer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday_writer', sa.DATE(), nullable=False))
        batch_op.drop_column('date_of_birth_writer')

    # ### end Alembic commands ###
