"""Add audit logs table

Revision ID: 4a1206fd7d12
Revises: f123456789ab
Create Date: 2025-11-02 19:13:33.359281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1206fd7d12'
down_revision = 'f123456789ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_audit_logs',
    sa.Column('ccn_audit_log', sa.Integer(), nullable=False),
    sa.Column('ccn_user', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('additional_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ccn_user'], ['tbl_users.ccn_user'], ),
    sa.PrimaryKeyConstraint('ccn_audit_log')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_audit_logs')
    # ### end Alembic commands ###
