"""Adding test_002

Revision ID: 6425802855d2
Revises: 701bead2cb00
Create Date: 2024-12-08 01:45:44.778383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6425802855d2'
down_revision = '701bead2cb00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_category', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_categories', schema=None) as batch_op:
        batch_op.drop_column('description_category')

    # ### end Alembic commands ###
