"""Add attribute account_id using generate password hash method

Revision ID: 8733d4fdf3ec
Revises: d65628522b80
Create Date: 2025-02-24 14:52:40.826268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8733d4fdf3ec'
down_revision = 'd65628522b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.String(length=300), nullable=False))
        batch_op.create_unique_constraint(None, ['account_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
