"""empty message

Revision ID: 9bda56f433ec
Revises: 
Create Date: 2024-01-07 02:43:17.630506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bda56f433ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_user',
    sa.Column('ccn_user', sa.Integer(), nullable=False),
    sa.Column('email_user', sa.String(length=100), nullable=False),
    sa.Column('password_user', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('ccn_user')
    )
    op.create_table('tbl_post',
    sa.Column('ccn_post', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('rel_users', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rel_users'], ['tbl_user.ccn_user'], ),
    sa.PrimaryKeyConstraint('ccn_post')
    )
    op.create_table('tbl_comment',
    sa.Column('ccn_comment', sa.Integer(), nullable=False),
    sa.Column('text_comment', sa.String(length=200), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('rel_authors', sa.Integer(), nullable=False),
    sa.Column('ccn_post', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ccn_post'], ['tbl_post.ccn_post'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rel_authors'], ['tbl_user.ccn_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ccn_comment')
    )
    op.create_table('tbl_likes',
    sa.Column('ccn_like', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('ccn_author', sa.Integer(), nullable=False),
    sa.Column('ccn_post', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ccn_author'], ['tbl_user.ccn_user'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ccn_post'], ['tbl_post.ccn_post'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ccn_like')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_likes')
    op.drop_table('tbl_comment')
    op.drop_table('tbl_post')
    op.drop_table('tbl_user')
    # ### end Alembic commands ###
