"""Add pumps table with all specifications

Revision ID: ab01df4cfbf0
Revises: 8733d4fdf3ec
Create Date: 2025-07-29 13:12:15.504561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab01df4cfbf0'
down_revision = '8733d4fdf3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_pumps',
    sa.Column('ccn_pump', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('serial_number', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('flow_rate', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('efficiency', sa.Float(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('current', sa.Float(), nullable=False),
    sa.Column('power_factor', sa.Float(), nullable=False),
    sa.Column('last_maintenance', sa.DateTime(), nullable=False),
    sa.Column('next_maintenance', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.ccn_user'], ),
    sa.PrimaryKeyConstraint('ccn_pump')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_pumps')
    # ### end Alembic commands ###
