"""First migration

Revision ID: b9f082d1b14b
Revises: 
Create Date: 2023-10-09 20:05:45.957259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f082d1b14b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_user',
    sa.Column('ccn_user', sa.Integer(), nullable=False),
    sa.Column('email_user', sa.String(length=100), nullable=False),
    sa.Column('terms_and_conditions', sa.String(length=10), nullable=False),
    sa.Column('profile_picture_user', sa.String(length=255), nullable=True),
    sa.Column('password_user', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('ccn_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_user')
    # ### end Alembic commands ###
