"""Add token block list table

Revision ID: c4c1e34c3cbe
Revises: d622e0c8a80c
Create Date: 2025-02-08 19:40:45.027983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c1e34c3cbe'
down_revision = 'd622e0c8a80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_token_block_list',
    sa.Column('ccn_token_block_list', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ccn_token_block_list')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_token_block_list')
    # ### end Alembic commands ###
