"""quit nullable option middle name user

Revision ID: d101e19c9215
Revises: e8b13a170146
Create Date: 2024-11-06 16:39:04.049631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd101e19c9215'
down_revision = 'e8b13a170146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_user', schema=None) as batch_op:
        batch_op.alter_column('middle_name_user',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_user', schema=None) as batch_op:
        batch_op.alter_column('middle_name_user',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
