"""Inlude tbl_writer and tbl_reader

Revision ID: d1346693f38e
Revises: c3485f87019f
Create Date: 2023-09-25 11:07:05.233735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1346693f38e'
down_revision = 'c3485f87019f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_reader',
    sa.Column('ccn_reader', sa.Integer(), nullable=False),
    sa.Column('ccn_type_id', sa.Integer(), nullable=True),
    sa.Column('number_id_reader', sa.BigInteger(), nullable=False),
    sa.Column('first_name_reader', sa.String(length=60), nullable=False),
    sa.Column('middle_name_reader', sa.String(length=60), nullable=True),
    sa.Column('first_last_name_reader', sa.String(length=60), nullable=False),
    sa.Column('second_last_name_reader', sa.String(length=60), nullable=True),
    sa.Column('birthday_reader', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('auto_perceived_gender', sa.Integer(), nullable=True),
    sa.Column('email_reader', sa.String(length=100), nullable=False),
    sa.Column('cellphone_reader', sa.BigInteger(), nullable=False),
    sa.Column('informed_consent_law_1581', sa.String(length=10), nullable=False),
    sa.Column('profile_picture_reader', sa.String(length=255), nullable=True),
    sa.Column('password_reader', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['auto_perceived_gender'], ['tbl_auto_perceived_gender.ccn_auto_perceived_gender'], ),
    sa.ForeignKeyConstraint(['ccn_type_id'], ['tbl_type_id.ccn_type_id'], ),
    sa.PrimaryKeyConstraint('ccn_reader'),
    sa.UniqueConstraint('number_id_reader')
    )
    op.create_table('tbl_writer',
    sa.Column('ccn_writer', sa.Integer(), nullable=False),
    sa.Column('ccn_type_id', sa.Integer(), nullable=True),
    sa.Column('number_id_writer', sa.BigInteger(), nullable=False),
    sa.Column('first_name_writer', sa.String(length=60), nullable=False),
    sa.Column('middle_name_writer', sa.String(length=60), nullable=True),
    sa.Column('first_last_name_writer', sa.String(length=60), nullable=False),
    sa.Column('second_last_name_writer', sa.String(length=60), nullable=True),
    sa.Column('birthday_writer', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('auto_perceived_gender', sa.Integer(), nullable=True),
    sa.Column('email_writer', sa.String(length=100), nullable=False),
    sa.Column('cellphone_writer', sa.BigInteger(), nullable=False),
    sa.Column('informed_consent_law_1581', sa.String(length=10), nullable=False),
    sa.Column('profile_picture_writer', sa.String(length=255), nullable=True),
    sa.Column('password_writer', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['auto_perceived_gender'], ['tbl_auto_perceived_gender.ccn_auto_perceived_gender'], ),
    sa.ForeignKeyConstraint(['ccn_type_id'], ['tbl_type_id.ccn_type_id'], ),
    sa.PrimaryKeyConstraint('ccn_writer'),
    sa.UniqueConstraint('number_id_writer')
    )
    with op.batch_alter_table('tbl_customer', schema=None) as batch_op:
        batch_op.drop_index('number_id_customer')

    op.drop_table('tbl_customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_customer',
    sa.Column('ccn_customer', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ccn_type_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_id_customer', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('first_name_customer', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('middle_name_customer', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('first_last_name_customer', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('second_last_name_customer', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('birthday_customer', sa.DATE(), nullable=False),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auto_perceived_gender', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email_customer', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('cellphone_customer', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('informed_consent_law_1581', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('profile_picture_customer', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password_customer', mysql.VARCHAR(length=300), nullable=False),
    sa.ForeignKeyConstraint(['auto_perceived_gender'], ['tbl_auto_perceived_gender.ccn_auto_perceived_gender'], name='tbl_customer_ibfk_1'),
    sa.ForeignKeyConstraint(['ccn_type_id'], ['tbl_type_id.ccn_type_id'], name='tbl_customer_ibfk_2'),
    sa.PrimaryKeyConstraint('ccn_customer'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tbl_customer', schema=None) as batch_op:
        batch_op.create_index('number_id_customer', ['number_id_customer'], unique=False)

    op.drop_table('tbl_writer')
    op.drop_table('tbl_reader')
    # ### end Alembic commands ###
