"""Add permissions and role_permissions tables

Revision ID: e665452784eb
Revises: 0ec259cbfcff
Create Date: 2025-08-15 13:39:26.337331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e665452784eb'
down_revision = '0ec259cbfcff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_permissions',
    sa.Column('ccn_permission', sa.Integer(), nullable=False),
    sa.Column('permission_name', sa.String(length=50), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ccn_permission'),
    sa.UniqueConstraint('permission_name')
    )
    op.create_table('tbl_roles',
    sa.Column('ccn_role', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ccn_role')
    )
    op.create_table('tbl_role_permissions',
    sa.Column('ccn_role_permission', sa.Integer(), nullable=False),
    sa.Column('ccn_role', sa.Integer(), nullable=False),
    sa.Column('ccn_permission', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ccn_permission'], ['tbl_permissions.ccn_permission'], ),
    sa.ForeignKeyConstraint(['ccn_role'], ['tbl_roles.ccn_role'], ),
    sa.PrimaryKeyConstraint('ccn_role_permission')
    )
    op.create_table('tbl_user_roles',
    sa.Column('ccn_user_role', sa.Integer(), nullable=False),
    sa.Column('ccn_user', sa.Integer(), nullable=False),
    sa.Column('ccn_role', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ccn_role'], ['tbl_roles.ccn_role'], ),
    sa.ForeignKeyConstraint(['ccn_user'], ['tbl_users.ccn_user'], ),
    sa.PrimaryKeyConstraint('ccn_user_role')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_user_roles')
    op.drop_table('tbl_role_permissions')
    op.drop_table('tbl_roles')
    op.drop_table('tbl_permissions')
    # ### end Alembic commands ###
