"""tbl_user changes

Revision ID: f3c96feabb9d
Revises: b9f082d1b14b
Create Date: 2023-11-11 18:14:34.602139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3c96feabb9d'
down_revision = 'b9f082d1b14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_user', schema=None) as batch_op:
        batch_op.drop_column('terms_and_conditions')
        batch_op.drop_column('profile_picture_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_user', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('terms_and_conditions', mysql.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
