"""Fixind tbl_writer relationships with tbl_type_id

Revision ID: f55cd62645d3
Revises: 45cba2cc3b6b
Create Date: 2023-09-27 22:30:32.797256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f55cd62645d3'
down_revision = '45cba2cc3b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_type_id', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_type', sa.String(length=3), nullable=False))
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_type_id', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', mysql.VARCHAR(length=3), nullable=False))
        batch_op.drop_column('id_type')

    # ### end Alembic commands ###
