"""Add token block list table

Revision ID: f8b915a79769
Revises: c4c1e34c3cbe
Create Date: 2025-02-08 19:41:36.237327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b915a79769'
down_revision = 'c4c1e34c3cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_token_block_list',
    sa.Column('ccn_token_block_list', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=300), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ccn_token_block_list')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_token_block_list')
    # ### end Alembic commands ###
