name: Deploy to EC2

on:
  workflow_run:
    workflows: ["CD - Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_PORTFOLIO }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2 via SSH
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
            docker pull $DOCKERHUB_USERNAME/portfolio-backend:latest
            docker pull $DOCKERHUB_USERNAME/portfolio-frontend:latest
            # Ajusta la ruta de docker-compose.yml si es necesario
            docker compose -f /home/ubuntu/Documents/Github/ruizdev7-portfolio/docker-compose.yml down
            docker compose -f /home/ubuntu/Documents/Github/ruizdev7-portfolio/docker-compose.yml up -d
          EOF
